/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.6/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    id("org.jetbrains.kotlin.jvm") version "1.9.23"

    application
}

repositories {
    mavenCentral()
}

dependencies {

}

application {
    // Define the main class for the application.
    mainClass = "MainKt"
}
